import Head from 'next/head'
import Image from 'next/image'
import Bar from './Components/Bar'
import Footer from './Components/Footer'
import Hero from './Components/Hero'
import Navbar from './Components/Navbar'


export default function Home() {
  return (
    <>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
      <Navbar />
      <Bar />
      <Hero />
      <Footer />
      </>
    </>
  )
}
